// DevPaths.swift
// devclean
//
// Single source of truth for every filesystem path the app touches.
// All paths are lazy computed properties so ~ is expanded at runtime.

import Foundation

enum DevPaths {

    // MARK: - Xcode

    /// ~/Library/Developer/Xcode/DerivedData
    static var xcodeDerivedData: String {
        "~/Library/Developer/Xcode/DerivedData"
    }

    /// ~/Library/Developer/Xcode/Archives
    static var xcodeArchives: String {
        "~/Library/Developer/Xcode/Archives"
    }

    /// ~/Library/Developer/Xcode/iOS DeviceSupport
    static var xcodeDeviceSupport: String {
        "~/Library/Developer/Xcode/iOS DeviceSupport"
    }

    /// ~/Library/Developer/CoreSimulator/Devices
    static var xcodeSimulatorDevices: String {
        "~/Library/Developer/CoreSimulator/Devices"
    }

    /// ~/Library/Caches/com.apple.dt.Xcode
    static var xcodeCaches: String {
        "~/Library/Caches/com.apple.dt.Xcode"
    }

    // MARK: - Android

    /// ~/.gradle/caches
    static var gradleCaches: String {
        "~/.gradle/caches"
    }

    /// ~/.gradle/wrapper/dists
    static var gradleWrappers: String {
        "~/.gradle/wrapper/dists"
    }

    /// ~/.android/avd
    static var androidEmulators: String {
        "~/.android/avd"
    }

    /// ~/.android/cache
    static var androidCache: String {
        "~/.android/cache"
    }

    // MARK: - Flutter

    /// ~/.pub-cache
    static var flutterPubCache: String {
        "~/.pub-cache"
    }

    /// ~/flutter/bin/cache  (assumes default Flutter SDK location)
    static var flutterBinCache: String {
        "~/flutter/bin/cache"
    }

    // MARK: - All categories (used by AppContainer to seed CleanableCategory list)

    static var allCategories: [CleanableCategory] {
        [
            CleanableCategory(
                id: "xcode.deriveddata",
                name: "Derived Data",
                description: "Build artifacts generated by Xcode. Safe to delete — Xcode regenerates them.",
                tool: .xcode,
                targetPaths: [xcodeDerivedData],
                items: []
            ),
            CleanableCategory(
                id: "xcode.archives",
                name: "Archives",
                description: "App archives created when archiving for distribution.",
                tool: .xcode,
                targetPaths: [xcodeArchives],
                items: []
            ),
            CleanableCategory(
                id: "xcode.devicesupport",
                name: "iOS Device Support",
                description: "Symbol files downloaded for connected devices. Old OS versions are safe to remove.",
                tool: .xcode,
                targetPaths: [xcodeDeviceSupport],
                items: []
            ),
            CleanableCategory(
                id: "xcode.simulators",
                name: "Simulators",
                description: "Simulator device images. Unused simulators can be removed.",
                tool: .xcode,
                targetPaths: [xcodeSimulatorDevices],
                items: []
            ),
            CleanableCategory(
                id: "xcode.caches",
                name: "Xcode Caches",
                description: "General Xcode disk caches.",
                tool: .xcode,
                targetPaths: [xcodeCaches],
                items: []
            ),
            CleanableCategory(
                id: "android.gradle.caches",
                name: "Gradle Caches",
                description: "Downloaded dependencies and task outputs cached by Gradle.",
                tool: .android,
                targetPaths: [gradleCaches],
                items: []
            ),
            CleanableCategory(
                id: "android.gradle.wrappers",
                name: "Gradle Wrappers",
                description: "Gradle distribution zips downloaded by the Gradle wrapper.",
                tool: .android,
                targetPaths: [gradleWrappers],
                items: []
            ),
            CleanableCategory(
                id: "android.emulators",
                name: "Android Emulators",
                description: "AVD images for Android Virtual Devices.",
                tool: .android,
                targetPaths: [androidEmulators],
                items: []
            ),
            CleanableCategory(
                id: "flutter.pubcache",
                name: "Pub Cache",
                description: "Flutter/Dart package cache. Re-downloadable via `pub get`.",
                tool: .flutter,
                targetPaths: [flutterPubCache],
                items: []
            ),
            CleanableCategory(
                id: "flutter.bincache",
                name: "Flutter SDK Cache",
                description: "Flutter tool artifacts. Regenerated automatically on next use.",
                tool: .flutter,
                targetPaths: [flutterBinCache],
                items: []
            ),
        ]
    }
}
